- Twitterbot
- facebookexternalhit
- TweetmemeBot
- UnwindFetchor
- Googlebot
- PaperLiBot
- TweetedTimes
- Twitterrific
- Twitturly
- BuiltWith
- UnwindFetchor
- EventMachine
- Jakarta Commons
- MetaURL API
- JS-Kit URL Resolver
- Ruby
- getprismatic.com